In [3]:
import pandas as pd
import numpy as np
dataframe = pd.read_csv('House.csv')

dataframe

,Unnamed: 0,Description,House_Type,Location,Price
0,0,5 BEDROOM HOUSE FOR RENT,5 Bedroom Semi Detached Duplex,Banana Island Ikoyi Lagos,"₦ 30,000,000/year"
1,1,4 BEDROOM HOUSE FOR RENT,4 Bedroom Terrace Duplex,Lekki Lagos,"₦ 9,500,000/year"
2,2,4 BEDROOM HOUSE FOR RENT,Serviced 4 Bedroom Terraced Duplex,Old Ikoyi Lagos,"₦ 20,000,000/year"
3,3,2 BEDROOM HOUSE FOR RENT,2 Bedroom Apartment,Ikate Lekki Lagos,"₦ 5,000,000/year"
4,4,COMMERCIAL PROPERTY FOR RENT,1 Room Office Space,"Liberty Road, Ibadan Oyo","₦ 400,000/year"
...,...,...,...,...,...
445,445,4 BEDROOM HOUSE FOR RENT,4 Bedroom Semi Detached Duplex With Bq,Osapa London Lekki Lagos,"₦ 6,500,000/year"
446,446,4 BEDROOM HOUSE FOR RENT,Luxury 4 Bedroom Semi Detached Duplex + Bq,"Chevron Toll Gate, Lekki Lagos","₦ 5,000,000/year"
447,447,3 BEDROOM HOUSE FOR RENT,Serviced 3 Bedroom Apartment,Victoria Island Lagos,"₦ 15,000,000/year"
448,448,4 BEDROOM HOUSE FOR RENT,Serviced 4 Bedroom Terrace Duplex,Ikate Lekki Lagos,"₦ 7,500,000/year"
449,449,4 BEDROOM HOUSE FOR RENT,Beautiful 4 Bedroom Semi Detached Duplex,"Chevron Toll Gate, Lekki Lagos","₦ 6,000,000/year"

In [6]:
dataframe.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 450 entries, 0 to 449
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Unnamed: 0   450 non-null    int64
 1   Description  450 non-null    object
 2   House_Type   450 non-null    object
 3   Location     450 non-null    object
 4   Price        450 non-null    object
dtypes: int64(1), object(4)
memory usage: 17.7+ KB